package com.example.collegeerp.ui.navigation

object Routes {
    const val AUTH = "auth"
    const val ADMIN_HOME = "admin"
    const val STAFF_HOME = "staff"
    const val STUDENT_HOME = "student"

    // Shared feature routes
    const val ADMISSIONS = "admissions"
    const val STUDENTS = "students"
    const val STUDENT_LIST = "student_list"
    const val STUDENT_DETAIL = "student/{studentId}"
    const val PAYMENTS = "payments/{studentId}"
    const val HOSTEL = "hostel"
    const val HOSTEL_ROOMS = "hostel_rooms"
    const val HOSTEL_ALLOCATION = "hostel_allocation"
    const val DASHBOARD = "dashboard"
    const val STUDENT_DASHBOARD = "student_dashboard"
    const val ADMISSION_DASHBOARD = "admission_dashboard"
    const val HOSTEL_DASHBOARD = "hostel_dashboard"
    const val ACCOUNTS_DASHBOARD = "accounts_dashboard"
    const val EXAM_DASHBOARD = "exam_dashboard"
    const val ADMIN_DASHBOARD = "admin_dashboard"
    const val NOTIFICATIONS = "notifications"
    const val ANALYTICS = "analytics"
    const val DOCUMENTS = "documents"
    const val ATTENDANCE = "attendance"
    const val PENDING_APPLICATIONS = "pending_applications"
    const val ADMISSION_REPORTS = "admission_reports"
    const val HOSTEL_MAINTENANCE = "hostel_maintenance"
    const val HOSTEL_REPORTS = "hostel_reports"
    const val PAYMENT_RECORDS = "payment_records"
    const val FINANCIAL_REPORTS = "financial_reports"
    const val OUTSTANDING_DUES = "outstanding_dues"
    const val RESULT_ANALYSIS = "result_analysis"
    const val TRANSCRIPTS = "transcripts"
    const val EXAMS = "exams"
    const val VIEW_EXAM_RECORDS = "view_exam_records"
    const val ADD_UPDATE_MARKS = "add_update_marks"
    const val PROFILE = "profile"
    const val PERSONAL_DETAILS = "personal_details"
}


